### ISSUE TITLE
not responsive lower then 350px width

### ISSUE THREAD

**Issue by Jainex17** [Jainex17/Busilearn#2]
when we go lower than 350px width it showing like this

![image](https://user-images.githubusercontent.com/81921291/212073874-56882d50-4942-4ad7-aeb6-a6cd9b630165.png)

I don't know what is causing this error 🥲

**Comment by davidthus** [comment]
what page is that?

**Comment by Jainex17** [comment]
> what page is that?

Home Page 
src/pages/Homepage

**Comment by Jainex17** [comment]
i solved this issue ✨
